---
- name: Preparation de l'Hote
  hosts: local
  become: yes
  roles:
    - deploy_infra

# - name: Installation et configuration MicroCloud
#   hosts: nodes
#   roles:
#     - microcloud

# - name: Déploiement Cloud
#   hosts: node1
#   roles:
#     - vms