---
# ==============================================================================
# 1. CRÉATION DES MACHINES VIRTUELLES LXD
# ==============================================================================
- name: Initialisation LOcale
  hosts: local
  become: yes

  tasks:
    - name: Installation snapd
      apt:
        name: snapd
        state: present
        update_cache: yes

    - name: Installation LXD
      snap:
        name: lxd
        state: present
        classic: no

    - name: Add current user to lxd group
      user:
        name: "{{ ansible_user_id }}"
        groups: lxd
        append: yes

    - name: Initialize LXD (non-interactive)
      command: lxd init --auto
      args:
        creates: /var/snap/lxd/common/lxd/storage-pools/default
  

    - name: Create network for the cluster
      ansible.builtin.command:
        cmd: lxc network create microbr0 ipv4.address=10.0.5.1/24 ipv4.nat=false ipv6.address=none
      register: create_microbr0
      failed_when: create_microbr0.rc != 0 and "already exists" not in create_microbr0.stderr
      changed_when: create_microbr0.rc == 0

- name: Gestion du stockage LXD
  hosts: localhost
  become: yes
  tasks:
    - name: Vérifier si le pool 'disks' existe déjà
      ansible.builtin.shell: "lxc storage show disks"
      register: storage_check
      ignore_errors: yes
      changed_when: false

    - name: Créer le pool de stockage ZFS 'disks'
      ansible.builtin.shell: "lxc storage create disks zfs size=100GiB"
      when: storage_check.rc != 0

    - name: Configurer la taille par défaut des volumes (10GiB)
      ansible.builtin.shell: "lxc storage set disks volume.size 10GiB"

    - name: Création des volumes locaux (local1 à local4)
      ansible.builtin.shell: |
        lxc storage volume show disks local{{ item }} >/dev/null 2>&1 || \
        lxc storage volume create disks local{{ item }} --type block
      loop: "{{ range(1, 5) | list }}"
      changed_when: false

    - name: Création des volumes distants (remote1 à remote3 - 20GiB)
      ansible.builtin.shell: |
        lxc storage volume show disks remote{{ item }} >/dev/null 2>&1 || \
        lxc storage volume create disks remote{{ item }} --type block size=20GiB
      loop: "{{ range(1, 4) | list }}"
      changed_when: false
    

# --- PHASE 2 : INSTALLATION DU CLUSTER SUR LES NŒUDS ---
- name: Installation de l'infrastructure MicroCloud
  hosts: nodes
  become: yes
  gather_facts: yes
  roles:
    - common
    - cluster

# --- PHASE 3 : DÉPLOIEMENT DES VMS DE TEST ---
- name: Déploiement des VMs personnalisées
  hosts: node1
  become: yes
  vars:
    vms_to_deploy:
      - name: "test-vm-ha"
        user: "admin"
        pass: "Password123!"
        size: "15GiB"
        nb_disks: 2
  roles:
    - vms