---
# --- PHASE 1 : PRÉPARATION DE LA KALI ---
- name: Configuration de l'hôte Kali et création des nœuds
  hosts: localhost
  become: yes
  roles:
    - install_required

# --- PHASE 2 : INSTALLATION DU CLUSTER SUR LES NŒUDS ---
- name: Installation de l'infrastructure MicroCloud
  hosts: nodes
  become: yes
  gather_facts: yes
  roles:
    - common
    - cluster

# --- PHASE 3 : DÉPLOIEMENT DES VMS DE TEST ---
- name: Déploiement des VMs personnalisées
  hosts: node1
  become: yes
  vars:
    vms_to_deploy:
      - name: "test-vm-ha"
        user: "admin"
        pass: "Password123!"
        size: "15GiB"
        nb_disks: 2
  roles:
    - vms